### ISSUE TITLE
Find out why recipes are not reproducible and if we can fix them

### ISSUE THREAD

**Issue by tdejager** [prefix-dev/reproducible-builds#40] opened 2024-06-03 09:27 UTC
From preliminary results, some recipes already not seem reproducible e.g `pthreads-stubs`

Either we need to:

* Fix them, with a patch or w/e so they are reproducible or,
* Mark them as not reproducible and show that on the README somehow.

**Comment by nichmor** [comment] 2024-06-18 13:15
Closing because we create separate issue per recipe to track them better:
https://github.com/prefix-dev/reproducible-builds/issues/75

**Closed by nichmor** 2024-06-18 13:15 UTC
